# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "crdecide2026"
pages_build_output_dir = "./dist"
compatibility_date = "2024-01-01"
