# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "crdecide2026"
account_id = "ea6eae55e8f7e10753884e234cfb84f0"
pages_build_output_dir = "./dist"
compatibility_date = "2024-01-01"
